README.md
xenit-alfresco/templates/ingress/alfresco-ingress.yaml
xenit-alfresco/values.yaml

XM2C-127 make default backend in ingress in helm alfresco settable by values

 XM2C-127 make default backend in ingress in helm alfresco settable by values

---

README.md
xenit-alfresco/templates/transform-services/shared-file-store/shared-file-store-config.yaml
xenit-alfresco/templates/transform-services/transform-core-aio/transform-core-aio-deployment.yaml
xenit-alfresco/values.yaml

remove default settings for shared-file-store for cleanup from configmap so they can be personalized for individual deployments.
+ add liveness and readiness probe settings for transformcoreAio
+ changed default memory req for transformCoreAio

[XENOPS-1123] remove share-file-store cleanup interval from configmap

---

xenit-alfresco/templates/transform-services/transform-core-aio/transform-core-aio-deployment.yaml

syntax error in deploy file prohibited helm from creating manifest.

[XENOPS-1123] fix syntax error in deploy file

---

xenit-alfresco/templates/transform-services/transform-core-aio/transform-core-aio-deployment.yaml

latest version of transform-core-aio liveness probe does not fail after maxtransforms is reached while readiness probe does fail making the service unavailable instead of having the pod restarted.
Interim fix is to use readiness endpoint also for liveness checks untill problem is solved at Alfresco.

[OUPSLA-2] mitigate liveness probe transform-core-aio issue

---

xenit-alfresco/templates/ooi/cilium-network-policy.yml

Sharepoint online uses `<hostname>.gr.global.aa-rt.sharepoint.com` uri which is not mapped by the standard `*.sharepoint.com` pattern.

[EUIAUDIT23-7] correct cilium ooi connections to sharepoint online

---

xenit-alfresco/values.yaml

Added blocked URL.
Please have a look at this repo, there are 2 more URLS referenced, but I do not think they are relevant?
https://github.com/aborroy/search-services-replication?tab=readme-ov-file#solr-considerations
before/after test can be done in browser:
<hostname>/alfresco/wcs/api/solr/nextTransaction?fromCommitTime=0

updated set of restricted urls

---

CHANGELOG.md
README.md
xenit-alfresco/templates/ingress/alfresco-ingress.yaml
xenit-alfresco/templates/ingress/nginx-403-config.yaml
xenit-alfresco/templates/ingress/nginx-default-config.yaml
xenit-alfresco/templates/ingress/nginx-default-deployment.yaml
xenit-alfresco/templates/ingress/nginx-default-service.yaml
xenit-alfresco/values.yaml

Individual deployments should not set the cluster defaultBackend as this could lead to invalid redirects.
* defaultBackend is now mapped to the root / path instead.
* nginx-403 has been replaced with nginx-default and will also serve as 404
* access logging has been added to nginx-default

[Xenops 1164] remove defaultbackend and replace with nginx-default

---

README.md
xenit-alfresco/templates/active-mq/mq-deployment.yaml
xenit-alfresco/templates/storage/mq-volumes.yaml

Started from https://xenitsupport.jira.com/browse/KANSUP74-23
Kansspelcommissie uses an NFS mount for both the ACS, Solr & ActiveMQ data.
For ACS, the problem was previously addressed by disabling the persistent storage of the ACS pods & adding a replacement volume & mount for a PV(C) pointing to the NFS mount. However, this option does not seem to be possible for ActiveMQ with the current version of our Helm charts.
This PR:
- introduces the mq.additionalVolumes option;
- introduces the mq.additionalVolumeMounts option;
- introduces the persistentStorage.mq.additionalClaims option.
An alternative solution would have been to introduce NFS support in the volume helper. However, most templates for Kansspelcommissie have already been written, so investing time in this alternative approach …

KANSUP74-23: introduce additional pvcs activemq

---

CHANGELOG.md
README.md
xenit-alfresco/Chart.yaml
xenit-alfresco/templates/acs/acs-deployment.yaml
xenit-alfresco/templates/active-mq/mq-deployment.yaml
xenit-alfresco/templates/digital-workspace/digital-workspace-deployment.yaml
xenit-alfresco/templates/ingress/alfresco-ingress.yaml
xenit-alfresco/templates/ingress/nginx-default-config.yaml
xenit-alfresco/templates/ingress/nginx-default-deployment.yaml
xenit-alfresco/templates/ooi/ooi-deployment.yaml
xenit-alfresco/templates/postgres/postgresql-deployment.yaml
xenit-alfresco/templates/share/share-deployment.yaml
xenit-alfresco/templates/solr/solr-backup/solr-backup-cron.yml
xenit-alfresco/templates/solr/solr-stateful-set.yaml
xenit-alfresco/templates/sync-service/sync-service-deployment.yaml
xenit-alfresco/templates/transform-services/shared-file-store/shared-file-store-deployment.yaml
xenit-alfresco/templates/transform-services/transform-core-aio/transform-core-aio-deployment.yaml
xenit-alfresco/templates/transform-services/transform-router/transform-router-deployment.yaml
xenit-alfresco/values.yaml

Provides a helm value "hibernate" which will scale down all replicas to 0 and redirect ingress to a maintenance message.

[Xenops 1200] add hibernation mode to scale down replicas

---

README.md
xenit-alfresco/templates/acs/acs-config.yaml
xenit-alfresco/templates/active-mq/mq-config.yaml
xenit-alfresco/templates/active-mq/mq-deployment.yaml
xenit-alfresco/templates/active-mq/mq-secret.yaml
xenit-alfresco/templates/active-mq/mq-service.yaml
xenit-alfresco/templates/active-mq/network-policy.yml

revert of https://github.com/xenit-eu/helm-alfresco/commit/3a06728cbd6b62b84e7b1cfa86697e2efbad5254#diff-9ef0f4efa891d05e19dd019ca85c5a17562dad05294829dca4ff133984bb295dL1
except for 
GLOBAL_local.transform.service.enabled: 'true'
when community edition

XENOPS-1187 revert disable MQ on community edition

---

CHANGELOG.md
README.md
xenit-alfresco/templates/solr/solr-stateful-set.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-71
For DSNY, we need an option to enforce hostname anti-affinity for the Solr pods.
The goal of this PR is to support this functionality.

[NYS2AWS-71] allow node anti-affinity for Solr pods

---

CHANGELOG.md
xenit-alfresco/templates/ingress/alfresco-ingress.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-74
Version 0.8.0 caused a quote-related problem in regards to the annotations for the ingress.
This version addresses that problem.

[NYS2AWS-74] enforce quotes for ingress annotations

---

CHANGELOG.md
xenit-alfresco/templates/solr/solr-stateful-set.yaml

After a restore from backup the SOLR index folder sometimes points to "restore.xxxx" instead of "index".
In order to remove any remaining write.lock files after restart, the mechanism should find instead of a hardcoded rm <path>

[XENOPS-1238] SOLR use "find" to delete write.lock

---

CHANGELOG.md
README.md
xenit-alfresco/templates/storage/alfresco-volumes.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-125
Problem: PVC's are namespace-specific, but PV's are not (cluster-wide). 
For DSNY, `alfresco-pv` was already used by the development environment. Helm added an annotation to that PV to prevent it from being used by other releases / namespaces. However, since `alfresco-pv` is hardcoded, the staging environment could not be installed.
Solution (discussed with Gert): change the prefix of the PV and PVC so that they default to "alfresco" (for legacy reasons), but allow a custom prefix for other environments.

[NYS2AWS-125] allow custom alfresco-pv names

---

xenit-alfresco/templates/storage/storage-class.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-121
Problem: if you install the AWS EFS storage class using `helm-alfresco`, you can only use that storage class in the current namespace.
Creating a new storage class with a different name does not seem to fix this issue, since K8S starts complaining about a missing filesystem ID (i.e., you apparently should create a storage class for each volume).
We also can't completely remove the storage class from `helm-alfresco`, since it's being used by another customer.
Therefore, I decided to make it toggleable.

NYS2AWS-121 remove efs storage class

---

CHANGELOG.md
xenit-alfresco/templates/active-mq/mq-deployment.yaml
xenit-alfresco/templates/storage/mq-volumes.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-130
Same problem as before with Alfresco: PVC's are namespace-specific, but PV's are not. Enabling ActiveMQ creates a persistent volume `mq-pv` that prevents any other namespace to ever create this PV again.
Solution: allow the name of the ActiveMQ PV and PVC to be specified.

[NYS2AWS-130] allow the specification of the ActiveMQ PV(C) names

---

CHANGELOG.md
README.md
xenit-alfresco/Chart.yaml
xenit-alfresco/templates/acs/acs-config.yaml
xenit-alfresco/templates/acs/acs-deployment.yaml
xenit-alfresco/templates/acs/acs-service.yaml
xenit-alfresco/values.yaml

Sets a port for the acs inbound email system on the acs deployment and service, and injects it in the configmap for acs.
Ingress config is not included since it depends on the ingress implementation and installation. 
(eg nginx addon requires changes in the daemonset & configmap, nginx chart requires custom resource.)

KANSUP74-37 add configurable port for acs inbound email

---

CHANGELOG.md
README.md
xenit-alfresco/templates/active-mq/mq-deployment.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-146
DSNY's proxy is acting up again, so it's not always possible to fetch the `busybox` image.
Solution: make the image registry / repository / tag configurable so that we can refer to their own Artifactory.

[NYS2AWS-146] add support for custom ActiveMQ init. container image

---

CHANGELOG.md
README.md
xenit-alfresco/templates/ingress/nginx-default-deployment.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-147
I'm trying to fix this, which is caused by OTI's problematic proxy setup:

[NYS2AWS-147] added support for custom NGINX image

---

CHANGELOG.md
README.md
xenit-alfresco/templates/ingress/alfresco-ingress.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/NYS2AWS-192
The problem is that DSNY wants two hostnames to point to the Alfresco ingress.
The first one is a generic ecm.dsnyad.nycnet. This one is currently still pointing to the old production servers; however, at production day, they want to update this one to also point to our ingress.
The second one is the specific ecmaws-prod.dsnyad.nycnet, which we are already currently using.
To limit the impact of switching hostnames during production day, I want to modify the ingress resource, so that it can listen to multiple hostnames.

NYS2AWS-192: Allow multiple ingress hostnames

---

CHANGELOG.md
README.md
xenit-alfresco/Chart.yaml
xenit-alfresco/templates/acs/acs-deployment.yaml
xenit-alfresco/values.yaml

https://xenitsupport.jira.com/browse/DSNYHD-80
Not actually caused by DSNYHD-80, but was noticed while upgrading the Helm charts in the DSNY project.
Node anti-affinity does not make sense if ACS is not clustered, and only adds more constraints on ACS redeployments. Therefore, we make it optional here.

[DSNYHD-80] Make ACS hostname anti-affinity optional
